spring.datasource.username: root
spring.datasource.password: Manal@11
spring.datasource.url: jdbc:mysql://localhost:3306/aidizital
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show-sql: true
server.port:8082
